### ISSUE TITLE
phone model

### ISSUE THREAD

**Issue by leonmayo** [Internaut401/CTF_Writeup#2]
you can find the phone model by finding his git hub, where there's a rep called /Yakuhito/phonemodel.
if you look at the previous commits to the rep, you'll find this page: https://github.com/Yakuhito/phonemodel/commit/6a6b8d18f7affe43cb54eef79625bf05f373695e
"model7" as the commit data, and "Pro version" at the commit comment

**Comment by Internaut401** [comment]
Thanks! In this case there are a few model so my "bruteforce" works. But thank you for the hint, next time i'll do better.
